DROP TABLE IF EXISTS users, items, bookings;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    name  VARCHAR(255)                                           NOT NULL,
    email VARCHAR(255) UNIQUE                                    NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    name        VARCHAR(255)                                           NOT NULL,
    description VARCHAR(255)                                           NOT NULL,
    available   BOOLEAN                                                NOT NULL,
    owner_id    BIGINT                                                 NOT NULL,
    foreign key (owner_id) references users (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    start     TIMESTAMP WITHOUT TIME ZONE                            NOT NULL,
    "end"     TIMESTAMP WITHOUT TIME ZONE                            NOT NULL,
    item_id   BIGINT                                                 NOT NULL,
    booker_id BIGINT                                                 NOT NULL,
    status    varchar(20)                                            NOT NULL,
    foreign key (item_id) references items (id),
    foreign key (booker_id) references users (id)
);

CREATE TABLE IF NOT EXISTS comments(
    id      BIGINT  GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    text    varchar                                                 NOT NULL,
    item_id BIGINT                                                  NOT NULL,
    author_id BIGINT                                                NOT NULL,
    created TIMESTAMP                                               NOT NULL,
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (author_id) REFERENCES users(id)
);
